services:
  messages-api-php:
    container_name: messages-api-php
    image: messages-api-php-image
    build:
      context: ./php
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/var/www/html
    networks:
      - sandbox-network

  messages-api-nginx:
    container_name: messages-api-nginx
    image: nginx:latest
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.messages-api.rule=Host(`messages.me`) && PathPrefix(`/api`)"
      - "traefik.http.routers.messages-api.entrypoints=web"
      - "traefik.http.services.messages-api.loadbalancer.server.port=80"
    networks:
      - sandbox-network

networks:
  sandbox-network:
    external: true
