services:
  php:
    container_name: projet-4-php
    image: projet-4-php-image
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    networks:
      - sandbox-network

  nginx:
    container_name: projet-4-nginx
    image: nginx:latest
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projet4.rule=Host(`test1.rfess.fr`)"
      - "traefik.http.routers.projet4.entrypoints=web"
      - "traefik.http.services.projet4.loadbalancer.server.port=80"
    networks:
      - sandbox-network

networks:
  sandbox-network:
    external: true
